/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epicest.happybirthday;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author Jayar
 */
public class HappyBirthday extends javax.swing.JFrame implements Runnable {

 /**
  * Creates new form HappyBirthday
  */
 public HappyBirthday() {
  initComponents();
  try {
   setIconImage(ImageIO.read(HappyBirthday.class.getResourceAsStream("party.png")));
  } catch (IOException ex) {
   System.out.println(ex.getMessage() + " Icon Error");
  }
  setLocationRelativeTo(null);
  setVisible(true);
  HappyPanel.parent = this;
  start();
 }

 public long beginTime;
 public long curTime;
 public long timeTicks = 20;
 public long ticks = 0;

 public boolean running = true;

 public Thread start;

 public void start() {
  start = new Thread(this);
  start.start();
 }

 public volatile ArrayList<Conffetti> conffetti = new ArrayList<Conffetti>();

 @Override
 public void run() {
  beginTime = System.currentTimeMillis();
  for (int i = 0; i < 200; i++) {
   conffetti.add(new Conffetti());
  }
  playParty();
  while (running) {
   curTime = System.currentTimeMillis();
   for (Conffetti i : conffetti) {
    i.update();
   }
   happyPanel1.repaint();
   long neededTicks = ((curTime - beginTime) / 33);
   ticks++;
   while (neededTicks <= ticks) {
    curTime = System.currentTimeMillis();
    neededTicks = ((curTime - beginTime) / 33);
   }
  }
 }

 public static synchronized void playParty() {
  new Thread(new Runnable() {
   // The wrapper thread is unnecessary, unless it blocks on the
   // Clip finishing; see comments.
   public void run() {
    try {
     Clip clip = AudioSystem.getClip();
     AudioInputStream inputStream = AudioSystem.getAudioInputStream(new BufferedInputStream(HappyBirthday.class.getResourceAsStream("party.wav")));
     clip.open(inputStream);
     clip.start();
    } catch (Exception e) {
     System.err.println(e.getMessage()+ " Audio Error");
    }
   }
  }).start();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  happyPanel1 = new com.epicest.happybirthday.HappyPanel();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Celebrate!");
  setResizable(false);
  addWindowListener(new java.awt.event.WindowAdapter() {
   public void windowClosing(java.awt.event.WindowEvent evt) {
    formWindowClosing(evt);
   }
  });

  javax.swing.GroupLayout happyPanel1Layout = new javax.swing.GroupLayout(happyPanel1);
  happyPanel1.setLayout(happyPanel1Layout);
  happyPanel1Layout.setHorizontalGroup(
   happyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 450, Short.MAX_VALUE)
  );
  happyPanel1Layout.setVerticalGroup(
   happyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 250, Short.MAX_VALUE)
  );

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(happyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(happyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  running = false;
 }//GEN-LAST:event_formWindowClosing

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Windows Classic look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Windows Classic".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(HappyBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(HappyBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(HappyBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(HappyBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new HappyBirthday().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private com.epicest.happybirthday.HappyPanel happyPanel1;
 // End of variables declaration//GEN-END:variables
}
